### ISSUE TITLE
Support for mutation operations

### ISSUE THREAD

**Issue by hugovanversendaal** [dotwebstack/dotwebstack-framework#809]
Hi,

According to the [docs](https://github.com/dotwebstack/dotwebstack-framework/blob/v0.3/docs/core/operations.md) of dotwebstack core, the supported operations are `subscriptions` and `queries`. Are there plans to support mutation operations in the future as well?

Best regards,
Hugo

**Comment by joostfarla** [comment]
Hi Hugo, this framework is designed for publishing data and thus it only supports read operations (queries and subscriptions). However, since the schema and runtime wiring can be modified (by implementing the `GraphqlConfigurer` interface), you could theoretically add your own mutation logic.

**Comment by hugovanversendaal** [comment]
Thanks for the confirmation Joost! I will take the suggestion of implementing our own mutation logic to my team for further consideration.

**Comment by janvlug** [comment]
Hi @joostfarla, thanks for your answer. I have a few other questions:

1. Could you maybe give a rough estimation of how much work it would be to implement mutation logic in dotwebstack for some custom modifications via the `GraphqlConfigurer`?
2. Do you maybe have a recommendation of other _free open source software_ that does support mutation operations?

**Comment by joostfarla** [comment]
Hi @janvlug, that's quite hard to tell without knowing the details. Can you provide a brief description of the architecture & requirements?
